---
title: "Exercicio Controle de qualidade 2"
output: html_document
---

```{r}
PFE <- function(LIE,LSE,MI,DP){
  return(100*(pnorm(LSE,MI,DP,lower.tail = F)+pnorm(LIE,MI,DP,lower.tail = T)))
}
ICP <- function(LIE,LSE,MI,DP){
  icp <- c()
  valor <- c()
  d <- (LIE+LSE)/2
  CP <- (LSE-LIE)/(6*DP)
  CPK <- min((LSE-MI)/(3*DP),(MI-LIE)/(3*DP))
  CPM <- (LSE-LIE)/(6*sqrt((DP^2)+(d-MI)^2))
  icp <- c("CP","CPK","CPM")
  valor <- round(c(CP,CPK,CPM),3)
  resp <-data.frame(icp,valor)
  return(resp)
}

```

```{r}
misig <- function(LIE,LSE,CP,CPK,CPM,qpfe){
  
d <- (LIE+LSE)/2    
x <- c()
dp <- c()

if(qpfe!=0 && CPM!=0){
    a1 <- 1/(qpfe)^2
    a2 <- 1
    
    b1 <- 2 * LIE/qpfe^2
    b2 <- 2 * d
    
    c2 <- d^2
    c1 <- LIE^2/(qpfe)^2
    c3 <- ((LSE-LIE)/(6*CPM))^2
    
    a <- a1+a2
    b <- -(b1+b2)
    c <- c1+c2-c3  
    delta1 <- b^2-4*a*c
    
    x[1] <- (-b - sqrt(delta1))/(2*a)
    x[2] <- (-b + sqrt(delta1))/(2*a)
    dp <- (x -LIE)/(qpfe)
  
  resp <- data.frame(x,dp)
}
  if(CP==0){
    a1 <- 1/(3*CPK)^2
    a2 <- 1
    
    b1 <- 2*LSE/(3*CPK)^2
    b2 <- 2 * d
    
    c2 <- d^2
    c1 <- LSE^2/(3*CPK)^2
    c3 <- ((LSE-LIE)/(6*CPM))^2
    
    a <- a1+a2
    b <- -(b1+b2)
    c <- c1+c2-c3  
    delta1 <- b^2-4*a*c
    
    x[1] <- (-b - sqrt(delta1))/(2*a)
    x[2] <- (-b + sqrt(delta1))/(2*a)
    dp <- (x -LIE)/(3*CPK)
    
    resp <- data.frame(x,dp)
    
  }
  if(CPK==0){
    dp1 <- (LSE-LIE)/(6*CP)
    
    c1 <- (LSE-LIE)^2
    c2 <- (6*CPM)^2
    
    c <-dp1^2 + d^2  - c1/c2 
    b <- -2*d
    a <- 1
    
     delta1 <- b^2-4*a*c
    
    x[1] <- (-b - sqrt(delta1))/(2*a)
    x[2] <- (-b + sqrt(delta1))/(2*a)
    dp[1] <- dp1
    dp[2] <- dp1
    resp <- data.frame(x,dp1)
     
  }
  if(CPM ==0 ){
    dp <- a / (6*CP)
    xb <- LSE - (3 * CPK * dp)
    resp <- data.frame(x,dp)
  }
  return(resp)
}
```


```{r}
tabela <- read.csv("Tabela.csv",header = T,sep = ";",dec = ",")
```

#Questao 1
```{r}
xb1 <- 34.994
dp1 <- 0.11
lie1 <- 34.745
lse1 <- 35.183
PFE(lie1,lse1,xb1,dp1)
ICP(lie1,lse1,xb1,dp1)[2,]
dp1 <- 0.1128799
PFE(lie1,lse1,xb1,dp1)
ICP(lie1,lse1,xb1,dp1)[2,]

```
#Questao 2
```{r}
q2 <- read.csv("Questao2 lista 2.csv",header = T,sep = ",",dec = ",")
n2 <- 5
xb2 <- mean(q2$X)
rb2 <- mean(q2$R)
dp2 <- rb2/tabela$d2[n2-1]
xb2
dp2 <- 2.02

lie2 <- 131
lse2 <- 139
ICP(lie2,lse2,xb2,dp2)[-3,]
PFE(lie2,lse2,xb2,dp2)
```

```{r}
q2 <- read.csv("Questao2alista 2.csv",header = T,sep = ",",dec = ",")
n <- 5
n2 <- 5
xb2 <- mean(q2$X)
rb2 <- mean(q2$R)
dp2 <- rb2/tabela$d2[n2-1]
xb2
dp2 <- 2.02

lie2 <- 131
lse2 <- 139
ICP(lie2,lse2,xb2,dp2)[-3,]
PFE(lie2,lse2,xb2,dp2)
```


#Questao 3a
```{r}
n3 <- 6
m3 <- 30
Sxb3 <- 600
Sdp3 <-71.4 
xb3 <- Sxb3/m3
dp3 <- (Sdp3/m3)/(tabela$C4[n3-1])
lie3 <- 10.5
lse3 <- 25.5
ICP(lie3,lse3,xb3,dp3)
PFE(lie3,lse3,xb3,dp3)
```
#Questao 3b
```{r}
(lse3-xb3)/qnorm(0.01,lower.tail = F)
```


#Questao 4a
```{r}
xb4 <- 1000
dp4 <- 2
lie4 <- 994
lse4 <- 1006
ICP(lie4,lse4,xb4,dp4)[-3,]
PFE(lie4,lse4,xb4,dp4)
```

#Questao 4b
```{r}
xb4b <- 1002
ICP(lie4,lse4,xb4b,dp4)[-3,]
PFE(lie4,lse4,xb4b,dp4)
```

#Questao 4c
```{r}
dp4c <- 4
ICP(lie4,lse4,xb4b,dp4c)[-3,]
PFE(lie4,lse4,xb4b,dp4c)
```
#Questao 5
```{r}
lie5 <- 12
lse5 <- 24
Cpk5 <- 0.8
Cpm5 <- 0.857

misig(lie5,lse5,0,Cpk5,Cpm5,0)

```
#Questao 6
```{r}
lie6 <- 88
lse6 <- 112
Cp6 <- 1
Cpm6 <- 0.8
misig(lie,lse,Cp6,0,Cpm6,0)

PFE(lie6,lse6,misig(lie,lse,Cp6,0,Cpm6)[,1],misig(lie,lse,Cp6,0,Cpm6)[,2])
```

#Questao 7
```{r}
pfe7 <- 1.222/100
lie7 <- 88
lse7 <- 112
Cpm7 <- 0.8
qpfe7 <- qnorm(pfe7)
misig(lie7,lse7,0,0,Cpm7,qpfe7)
```
```{r}
d7 <- (lie7+lse7)/2
c1 <- c2 <- (d7-lie7)^2 
c3 <- ((lse7-lie7)/(6*Cpm7))^2

a <- 1 + qpfe7^2
b <- -2*(d7-lie7)* qpfe7
c <- c2-c3  
delta1 <- b^2-4*a*c

(-b - sqrt(delta1))/(2*a)
(-b + sqrt(delta1))/(2*a)

```




#Questao 8
```{r}
n <- 4
lic <- 96.16
lsc <- 107.84
dp <- 4
lie <- 91
lse <- 115
xb <- lic+6
zlic <- (lic-xb)/2
zlsc <- (lsc-xb)/2
100*(pnorm(zlsc,lower.tail = F) + pnorm(zlic))
PFE(lie,lse,xb,dp)
ICP(lie,lse,xb,dp)[3,]

k <- 3
xb1 <- 104
delta <- (xb1-xb)/dp
1 - (pnorm(-k - delta * sqrt(n))+pnorm(-k + delta * sqrt(n)))
PFE(lie,lse,xb1,dp)
ICP(lie,lse,xb1,dp)[3,]

```

